# Generated by Django 2.2 on 2020-04-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_aboutyou'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aboutyou',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
